#elasticsearch.clustername = mkyong-cluster
#elasticsearch.host = localhost
#elasticsearch.port = 9300

# Home directory of the embedded Elasticsearch instance. Default to the current working directory.
#spring.data.elasticsearch.properties.path.home=target/elastic
#spring.data.elasticsearch.properties.transport.tcp.connect_timeout=120s

elasticsearch:
  useEmbedded: true
  clustername: "demo-cluster"
  host: "localhost"
  port: 9300

spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # do not allow hibernate to change db schema! just validate it.
        ddl-auto: validate
  jackson:
    serialization:
      write_dates_as_timestamps: false

---
spring:
  profiles: dev
  datasource:
      url: jdbc:postgresql://localhost:5432/example
      username: example
      password: example
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false

logging:
  level:
    org:
      hibernate:
        type: info

